### ISSUE TITLE
seeing whitenoise in one channel on Jupyter

### ISSUE THREAD

**Issue by EMCP** [JuliaAudio/SampledSignals.jl#27] opened 2018-01-21 15:47 UTC
I successfully ran the `load()` call, but when using Jupyter Notebook noticed one channel had some strange white noise in it?

<img width="906" alt="screen shot 2018-01-21 at 4 47 08 pm" src="https://user-images.githubusercontent.com/3691722/35195906-bef4a760-feca-11e7-96b6-cceea2406d11.png">

I am pretty sure I didn't select mono.. so just trying to pinpoint why

**Comment by ssfrr** [comment] 2018-01-21 18:20
That's weird, are you able to attach the audio file and MWE for how you're loading it?

**Comment by EMCP** [comment] 2018-01-21 19:07
I uploaded an MWE to here

https://github.com/EMCP/AudioNotebooks_Julia/blob/master/playground.ipynb

the end result doesn't display but hopefully you understand it.. wondering if I need to ignore the `samplerate` field

**Comment by ssfrr** [comment] 2018-01-21 19:11
Is all that code required to reproduce the issue? i.e. if you start a fresh notebook with just:

```julia
using LibSndFile: load
load("/path/to/sndfile.wav")
```

does it do the same thing?

Also if this is a wav file you're generating from your code, it would be worth opening the file in an audio editor like audacity, so you can tell whether the problem is with saving or loading the file.

**Comment by EMCP** [comment] 2018-01-24 19:45
@ssfrr apologies on the delayed response, started a new gig this week and the commutes quite long.

I whittled it down and it still is occurring

<img width="738" alt="screen shot 2018-01-24 at 8 44 08 pm" src="https://user-images.githubusercontent.com/3691722/35353425-70d626a6-0147-11e8-9693-2cb7348e31a4.png">

**Comment by ssfrr** [comment] 2018-01-24 19:51
weird. is it possible to send a link to the WAV file in question? You could send it to me directly at XBw8u@accounts.ssfrr.com if you can't share it publicly.

**Comment by EMCP** [comment] 2018-01-24 20:04
<img width="941" alt="screen shot 2018-01-24 at 9 03 54 pm" src="https://user-images.githubusercontent.com/3691722/35354370-1a5ac4f0-014a-11e8-80dc-0c3798d68ec2.png">

emailed, just for my sanity I opened the sample in Audacity.. seems fine

**Comment by ssfrr** [comment] 2018-01-31 14:31
The good news here is that I can reproduce it. It doesn't seem to be a problem with the loading of the file or the internal representation in Julia, something is going wrong with how it's getting converted into the javascript display in the Jupyter notebook.

Looking into it...

**Comment by ssfrr** [comment] 2018-01-31 14:36
Seems to have to do with the Fixed-point representation - as a workaround you can convert to `Float32` (or `Float64`):

```julia
buf = Float32.(load("/home/sfr/Downloads/Ambient\ Shaker-80bpm.wav"))
```

**Comment by ssfrr** [comment] 2018-02-03 13:48
The issue is that file is a 32-bit integer format (not super common, but definitely something we should handle), and the current conversion machinery wasn't set up to work for that.

I pushed a fix to a branch a couple days ago, but it exposed another issue with 32-bit systems, so I think that needs to be fixed before I merge this into master. (see JuliaMath/FixedPointNumbers.jl#104).

**Closed** 2018-02-07 16:50 UTC

**Comment by ssfrr** [comment] 2018-02-07 16:54
Just tagged a [new release](https://github.com/JuliaLang/METADATA.jl/pull/13281) with this fix, so once it's merged you should get it with `Pkg.update()`
